# Generated by Django 5.2 on 2025-04-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_image_product_sub_image1_product_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
