# Generated by Django 5.2 on 2025-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cartitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
